### ISSUE TITLE
Failure to load rules on python3.5

### ISSUE THREAD

**Issue by avilaton** [erik/squabble#10]
Hi, thanks for building squabble first of all.
I had run it in the past and now I came back to give it another go. I found an issue running in 3.5 which is not affecting python3.8. The simplest form of test I can provide is 
```
from squabble import cli
cli.dispatch_args({"--verbose": True, "--list-presets": False, "--config": None, "--preset": None, "--reporter": None, "--list-rules": True})
```
returns empty for 3.5, while it prints rules for 3.8. I was unable to make further progress due to time constraints but I thought I could leave a note here just in case.
If I find out what is happening I'll be back for sure.

**Comment by avilaton** [comment]
Something is preventing Registry from running __init_class__ when rules are imported which prevents squabble from finding them later. This is what we see from the command line
```
$ squabble ./12345.sql --verbose
DEBUG:squabble.config:checking . for a config file
DEBUG:squabble.config:using "./.squabblerc" for configuration
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/bin/squabble", line 11, in <module>
    load_entry_point('squabble==1.4.0', 'console_scripts', 'squabble')()
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/lib/python3.5/site-packages/squabble/__main__.py", line 12, in main
    status = cli.main()
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/lib/python3.5/site-packages/squabble/cli.py", line 45, in main
    return dispatch_args(args)
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/lib/python3.5/site-packages/squabble/cli.py", line 86, in dispatch_args
    return run_linter(base_config, args['PATHS'], args['--expanded'])
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/lib/python3.5/site-packages/squabble/cli.py", line 111, in run_linter
    issues += lint.check_file(file_config, file_name, contents)
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/lib/python3.5/site-packages/squabble/lint.py", line 75, in check_file
    rules = _configure_rules(config.rules)
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/lib/python3.5/site-packages/squabble/lint.py", line 64, in _configure_rules
    cls = Registry.get_class(name)
  File "/home/user/.cache/pypoetry/virtualenvs/project-2ImR_qxG-py3.5/lib/python3.5/site-packages/squabble/rule.py", line 149, in get_class
    raise UnknownRuleException(name)
squabble.UnknownRuleException: unknown rule: "AddColumnDisallowConstraints"

```

**Comment by avilaton** [comment]
I know 3.5 is no longer recommended but enterprise life, you know. This fails on 3.5 due to init_subclass not being available, I'll send a PR with a patch.

**Comment by erik** [comment]
Thanks again for reporting this and working on this fix!
